Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 50
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
Style/SymbolArray:
  Enabled: true
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Enabled: false
